# Generated by Django 4.1.7 on 2023-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
